"""Structural protocol shared by native and portable design adapters."""
from pathlib import Path
from typing import Protocol, Self

from _lib.design_contract import DesignSpec


class DesignBackend(Protocol):
    model_suffix: str

    def __enter__(self) -> Self: ...
    def __exit__(self, *args) -> None: ...
    def inspect(self) -> dict: ...
    def evaluate(self, spec: DesignSpec) -> list[dict]: ...
    def set_focus(self, position: float) -> None: ...
    def save(self, path: Path) -> None: ...
    def load(self, path: Path) -> None: ...
    def get_parameter(self, surface: int, name: str) -> float: ...
    def set_parameter(self, surface: int, name: str, value: float) -> None: ...
