import { describe, expect, it } from "vitest";
import { spawnSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";

const root = path.resolve(__dirname, "..", "..");
const read = (p: string) => JSON.parse(fs.readFileSync(path.join(root, p), "utf8"));

describe("distribution manifests", () => {
  it("package.json has the required identity", () => {
    const pkg = read("package.json");
    expect(pkg.name).toBe("optical-design");
    expect(pkg.license).toBe("MIT");
    expect(pkg.engines.node).toBe(">=22");
    expect(pkg.bin).toEqual({ "optical-design": "bin/optical-design.mjs" });
    expect(pkg.files).toContain("skills");
  });
  it("plugin manifests agree with package.json", () => {
    const pkg = read("package.json");
    const agentPlugin = read("plugin.json");
    const claudePlugin = read(".claude-plugin/plugin.json");
    const marketplace = read(".claude-plugin/marketplace.json");
    expect(agentPlugin.name).toBe("optical-design");
    expect(agentPlugin.version).toBe(pkg.version);
    expect(claudePlugin.version).toBe(pkg.version);
    expect(claudePlugin.skills).toBe("./skills/");
    expect(marketplace.plugins[0].name).toBe("optical-design");
    expect(marketplace.plugins[0].source).toBe("./");
  });
  it("native plugins share the released skill and real local artwork", () => {
    const pkg = read("package.json");
    for (const file of [".codex-plugin/plugin.json", ".cursor-plugin/plugin.json"]) {
      const plugin = read(file);
      expect(plugin.name).toBe(pkg.name);
      expect(plugin.version).toBe(pkg.version);
      expect(plugin.skills).toBe("./skills/");
      expect(plugin.mcpServers).toBeUndefined();
    }
    const codex = read(".codex-plugin/plugin.json");
    for (const key of ["composerIcon", "logo", "logoDark"]) {
      const image = codex.interface[key];
      expect(image).toMatch(/^\.\/assets\/.+\.png$/u);
      expect(fs.readFileSync(path.join(root, image)).subarray(0, 8))
        .toEqual(Buffer.from([137, 80, 78, 71, 13, 10, 26, 10]));
    }
    const marketplace = read(".agents/plugins/marketplace.json");
    expect(marketplace.plugins[0].source).toEqual({ source: "url", url: "https://github.com/tangericm/optical-design.git" });
    expect(marketplace.plugins[0].policy.installation).toBe("AVAILABLE");
  });
  it("npm pack ships the skill and nothing local", () => {
    const result = spawnSync("npm", ["pack", "--dry-run", "--json", "--ignore-scripts"], {
      cwd: root, encoding: "utf8", shell: process.platform === "win32"
    });
    expect(result.status).toBe(0);
    const files: string[] = JSON.parse(result.stdout)[0].files.map((f: { path: string }) => f.path);
    for (const required of ["skills/optical-design/SKILL.md", "skills/optical-design/LICENSE", "LICENSE", "README.md", "SECURITY.md"]) {
      expect(files, `missing ${required}`).toContain(required);
    }
    expect(files.some(f => /^(evals|tests|node_modules|docs\/superpowers|\.github)\//u.test(f))).toBe(false);
    expect(files.some(f => f.startsWith('skills/optical-design/evals/'))).toBe(false);
    // python bytecode is generated by running the tests; it must never ship
    expect(files.every(f => !/(^|\/)__pycache__\/|\.pyc$/u.test(f)),
      `bytecode in tarball: ${files.filter(f => /(^|\/)__pycache__\/|\.pyc$/u.test(f)).join(", ")}`).toBe(true);
  });
  it("package.json excludes python bytecode", () => {
    expect(read("package.json").files).toEqual(
      expect.arrayContaining(["!skills/**/__pycache__/**", "!skills/**/*.pyc"]));
  });
});
